machine:
  node:
    version: 6.11.5
dependencies:
  pre:
    # see https://cloud.google.com/sdk/gcloud/reference
    - sudo /opt/google-cloud-sdk/bin/gcloud components update --quiet
    - sudo /opt/google-cloud-sdk/bin/gcloud components install beta --quiet
    - sudo /opt/google-cloud-sdk/bin/gcloud config set project aqueous-vial-195311
    # see https://circleci.com/docs/1.0/google-auth
    - echo $GCLOUD_SERVICE_KEY | base64 --decode --ignore-garbage > ${HOME}/gcloud-service-key.json
    - sudo /opt/google-cloud-sdk/bin/gcloud auth activate-service-account --key-file ${HOME}/gcloud-service-key.json
deployment:
  production:
    branch: master
    commands:
      # see https://cloud.google.com/sdk/gcloud/reference/beta/functions/deploy
      - sudo /opt/google-cloud-sdk/bin/gcloud functions deploy chuckNorrisJoke --trigger-http